# Site
repository: ISSuh/resume
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

timezone: Asia/Seoul

# Personal info
name: 서인석
title: Inseock Suh
email: yoyus5@naver.com
# website: https://issuh.github.io/
# website_title: Blog

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  ISSuh
# linkedin_username: jekyll

# Additional icon links
additional_links:
- title: Blog
  icon: fa-solid fa-blog
  url: https://issuh.github.io/

# - title: another 
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  
  5년의 경력을 가진 소프트웨어 개발자로 주로 여러 임베디드 리눅스 환경에서 클라이언트 사이드의 어플리케이션들을 개발하였습니다.

  항상 더 나은 소프트웨어를 위하여 주로 개인 프로젝트를 통해 업무와 관련된 주제나 관심있는 주제 혹은 다양한 기술에 대하여 직접 구현해보는 것으로 학습하고 있으며 개인 블로그를 운영하여 공부한 내용을 정리하고 있습니다.

  최근에는 임베디드 소프트웨어 개발자를 벗어나 백앤드 개발자로 새롭게 발돋움하기 위해 꾸준한 노력을 하고 있습니다.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
